JobPulse SRE Cluster
====================
Generated by Terraform

Nodes:
%{ for name, node in nodes ~}
  ${name}: ${node.name} (${node.ip}) - Role: ${node.role}
%{ endfor ~}

Access:
  API:        http://192.168.1.104:30500
  Grafana:    http://192.168.1.114:3000
  Prometheus: http://192.168.1.114:9090
